// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BattleshipGame.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BattleshipGameDbContext))]
    partial class BattleshipGameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BattleshipGame.Infrastructure.Persistence.Entities.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BoardSize")
                        .HasColumnType("integer")
                        .HasColumnName("board_size");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("OpponentStrategy")
                        .HasColumnType("integer")
                        .HasColumnName("opponent_strategy");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<int>("TargetSide")
                        .HasColumnType("integer")
                        .HasColumnName("target_side");

                    b.Property<int>("WinnerSide")
                        .HasColumnType("integer")
                        .HasColumnName("winner_side");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("games", (string)null);
                });

            modelBuilder.Entity("BattleshipGame.Infrastructure.Persistence.Entities.PlayerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_game_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ActiveGameId")
                        .IsUnique()
                        .HasFilter("active_game_id IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("BattleshipGame.Infrastructure.Persistence.Entities.PlayerGameHistoryEntry", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.HasKey("PlayerId", "GameId");

                    b.ToTable("player_game_history", (string)null);
                });

            modelBuilder.Entity("BattleshipGame.Infrastructure.Persistence.Entities.GameEntity", b =>
                {
                    b.OwnsOne("BattleshipGame.Infrastructure.Persistence.Entities.BoardJson", "OppBoard", b1 =>
                        {
                            b1.Property<Guid>("GameEntityId");

                            b1.Property<Guid>("Id");

                            b1.HasKey("GameEntityId");

                            b1.ToTable("games");

                            b1
                                .ToJson("opp_board")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("GameEntityId");

                            b1.OwnsMany("BattleshipGame.Infrastructure.Persistence.Entities.CellJson", "Cells", b2 =>
                                {
                                    b2.Property<Guid>("BoardJsonGameEntityId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Code")
                                        .IsRequired();

                                    b2.Property<Guid?>("ShipId");

                                    b2.Property<int>("State");

                                    b2.HasKey("BoardJsonGameEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("games");

                                    b2.WithOwner()
                                        .HasForeignKey("BoardJsonGameEntityId");
                                });

                            b1.OwnsMany("BattleshipGame.Infrastructure.Persistence.Entities.ShipJson", "Ships", b2 =>
                                {
                                    b2.Property<Guid>("BoardJsonGameEntityId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.PrimitiveCollection<string>("Codes")
                                        .IsRequired();

                                    b2.PrimitiveCollection<string>("Hits")
                                        .IsRequired();

                                    b2.Property<Guid>("Id");

                                    b2.Property<int>("Kind");

                                    b2.HasKey("BoardJsonGameEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("games");

                                    b2.WithOwner()
                                        .HasForeignKey("BoardJsonGameEntityId");
                                });

                            b1.Navigation("Cells");

                            b1.Navigation("Ships");
                        });

                    b.OwnsOne("BattleshipGame.Infrastructure.Persistence.Entities.BoardJson", "OwnBoard", b1 =>
                        {
                            b1.Property<Guid>("GameEntityId");

                            b1.Property<Guid>("Id");

                            b1.HasKey("GameEntityId");

                            b1.ToTable("games");

                            b1
                                .ToJson("own_board")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("GameEntityId");

                            b1.OwnsMany("BattleshipGame.Infrastructure.Persistence.Entities.CellJson", "Cells", b2 =>
                                {
                                    b2.Property<Guid>("BoardJsonGameEntityId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.Property<string>("Code")
                                        .IsRequired();

                                    b2.Property<Guid?>("ShipId");

                                    b2.Property<int>("State");

                                    b2.HasKey("BoardJsonGameEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("games");

                                    b2.WithOwner()
                                        .HasForeignKey("BoardJsonGameEntityId");
                                });

                            b1.OwnsMany("BattleshipGame.Infrastructure.Persistence.Entities.ShipJson", "Ships", b2 =>
                                {
                                    b2.Property<Guid>("BoardJsonGameEntityId");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd();

                                    b2.PrimitiveCollection<string>("Codes")
                                        .IsRequired();

                                    b2.PrimitiveCollection<string>("Hits")
                                        .IsRequired();

                                    b2.Property<Guid>("Id");

                                    b2.Property<int>("Kind");

                                    b2.HasKey("BoardJsonGameEntityId", "__synthesizedOrdinal");

                                    b2.ToTable("games");

                                    b2.WithOwner()
                                        .HasForeignKey("BoardJsonGameEntityId");
                                });

                            b1.Navigation("Cells");

                            b1.Navigation("Ships");
                        });

                    b.Navigation("OppBoard")
                        .IsRequired();

                    b.Navigation("OwnBoard")
                        .IsRequired();
                });

            modelBuilder.Entity("BattleshipGame.Infrastructure.Persistence.Entities.PlayerGameHistoryEntry", b =>
                {
                    b.HasOne("BattleshipGame.Infrastructure.Persistence.Entities.PlayerEntity", "Player")
                        .WithMany("GameHistory")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("BattleshipGame.Infrastructure.Persistence.Entities.PlayerEntity", b =>
                {
                    b.Navigation("GameHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
